export default {
  primary: '#1063FD',
  muted: '#3A5A92',
  background: '#EFEEF6',
  gray: '#6E6E73',
  lightGray: '#DCDCE2',
  green: '#4FEE57',
  lightGreen: '#DBFFCB',
  red: '#EF0827',
  yellow: '#FCC70B',
  light: {
    text: "#000",
    background: "#223B82",
  //  tint: tintColorLight,
    tabIconDefault: "#ccc",
   // tabIconSelected: tintColorLight,
  },
  dark: {
    text: "#fff",
    background: "#040e22",
    secondary: "#0D1F46",
 //   tint: tintColorDark,
    tabIconDefault: "#ccc",
   // tabIconSelected: tintColorDark,
  },
};
